### ISSUE TITLE
When users leave a server they don't have gear in it deletes them

### ISSUE THREAD

**Issue by jtbry** [jtbry/bdo_gearbot#13]
When users leave a server with the bot, even if they don't have their gear in that server, it will delete their gear. 

i.e
```
User A joins Server A which has the bot
User A joins Server B which has the bot
User A puts their gear in Server B
User A leaves Server A (They are then deleted from Server B)
```

**Comment by ImpossibleMushroom** [comment]
Need to edit the `guildMemberRemove` callback to only delete user's who have a matching `guild` in the database

[App.js Line 54](https://github.com/ImpossibleMushroom/bdo_gearbot/blob/master/app.js#L54)
